import { Component, signal } from '@angular/core';
/*
  FfButton is the Angular standalone directive wrapping the Stencil <ff-button> web component.
  It is auto-generated by @stencil/angular-output-target and contains zero styling or brand logic.
  The component logic (props, slots, shadow DOM) lives in the published @fuggetlenfe/components package.
  The visual identity comes from the CSS imports in styles.css (contract.css + brand-1 pack).
*/
import { FfButton } from '@fuggetlenfe/angular-wrapper';

type ThemeMode = 'light' | 'dark';

type ThemeOption = {
  label: string;
  value: ThemeMode;
};

@Component({
  selector: 'app-root',
  // FfButton is a standalone directive — no NgModule required.
  // It proxies Angular template bindings to the underlying web component via @ProxyCmp.
  imports: [FfButton],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class BrandOneShowcaseAppComponent {
  readonly activeTheme = signal<ThemeMode>('light');
  readonly themeOptions: readonly ThemeOption[] = [
    { label: 'Light', value: 'light' },
    { label: 'Dark', value: 'dark' },
  ];
  // Per-instance token overrides. These values are bound in the template via
  // [style.--ff-button-radius] etc., which overrides the brand pack values
  // for that specific <ff-button> instance only.
  readonly inlineTokenStyle = {
    paddingInline: '0.95rem',
    paddingBlock: '0.48rem',
    radius: '4px',
  };

  setTheme(selectedTheme: ThemeMode) {
    this.activeTheme.set(selectedTheme);
  }
}
